name: test workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'



jobs:


  testbuild:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: DEVELOP_TEST
    steps:


      - name: Checkout code
        uses: actions/checkout@master
        
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main

      - run: echo "name - ${{ steps.info.outputs.name }}"
      - run: echo "version - ${{ steps.info.outputs.version }}"


      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
        
        
      - name: Get current time
        id: time
        run: echo "time=$(date +'%H-%M')" >> $GITHUB_OUTPUT     
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Test Secret
        run: echo "date -> ${{ secrets.TEST_SECRET_ENV }}"


