name: test workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'



jobs:


  testbuild:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: DEVELOP_TEST
    steps:


      - name: Checkout code
        uses: actions/checkout@master

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.2.1
      # From now you can access the version
      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}
        
        
        

      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main

      - run: echo "name - ${{ steps.info.outputs.name }}"
      - run: echo "version - ${{ steps.info.outputs.version }}"
      - run: echo "description - ${{ steps.info.outputs.description }}"
      - run: echo "author - ${{ steps.info.outputs.author }}"
        
        
        
      - name: Get current time
        id: time
        run: echo "time=$(date +'%H-%M')" >> $GITHUB_OUTPUT     
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Test Secret
        run: echo "date -> ${{ secrets.TEST_SECRET_ENV }}"


