name: test workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'



jobs:


  testbuild:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: DEVELOP_TEST
    permissions:
      contents: write
    steps:


      - name: Checkout code
        uses: actions/checkout@master
        
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main

      - run: echo "name - ${{ steps.info.outputs.name }}"
      - run: echo "version - ${{ steps.info.outputs.version }}"


#       - uses: actions/checkout@v3
#       - uses: ncipollo/release-action@v1
#         with:
#           tag: "${{ steps.info.outputs.version }}"
# #           replacesArtifacts: 'true'
#           artifacts: "release.tar.gz,foo/*.txt"
#           bodyFile: "README.md"
          
        
        
      - name: Get current time
        id: time
        run: echo "time=$(date +'%H-%M')" >> $GITHUB_OUTPUT     
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Test Secret
        run: echo "date -> ${{ secrets.TEST_SECRET_ENV }}"
 


      - uses: iamkubi/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.info.outputs.version }}
          name: ${{ steps.info.outputs.version }}
          allow_override: 'true'


